### ISSUE TITLE
usage in the browser

### ISSUE THREAD

**Issue by iamstarkov** [patrickkettner/travis-ping#4]
Hey, thanks for package.

Can I use it in the browser? wiil it be safe for me?

**Comment by patrickkettner** [comment]
nah. it uses `travis-api`, which is node only

you'll wanna check out [travis' docs on web clients](http://docs.travis-ci.com/api/#api-clients)

cheers!

**Comment by iamstarkov** [comment]
Thank you!

**Comment by patrickkettner** [comment]
a pleasure :]

On Sat, Apr 25, 2015 at 12:56 AM, Vladimir Starkov <notifications@github.com
> wrote:

> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/patrickkettner/travis-ping/issues/4#issuecomment-96129544>
> .
>



-- 
patrick
